export const courseData = [
  {
    id: 1,
    courseName: 'Complete React Developer',
    instructorName: 'Andrei Neagoie',
    img: 'https://img-a.udemycdn.com/course/750x422/2365628_0b60_7.jpg',
    price: 12.0,
  },
  {
    id: 2,
    courseName: 'Complete Web Development Course',
    instructorName: 'Jhankar Mahbub',
    img:
      'https://bangla2.programming-hero.com/wp-content/uploads/2020/06/HTML_CSS_Cover.png',
    price: 8.0,
  },
  {
    id: 3,
    courseName: 'The Complete JavaScript Course 2020: Build Real Projects!',
    instructorName: 'Jonas Schmedtmann',
    img: 'https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg',
    price: 9.99,
  },
  {
    id: 4,
    courseName: 'JavaScript Understanding the Weird Parts',
    instructorName: 'Anthony Alicea',
    img: 'https://img-a.udemycdn.com/course/240x135/364426_2991_5.jpg',
    price: 9.99,
  },
  {
    id: 5,
    courseName: 'Modern JavaScript From The Beginning',
    instructorName: 'Brad Traversy',
    img: 'https://img-a.udemycdn.com/course/240x135/1463348_52a4_2.jpg',
    price: 9.99,
  },
  {
    id: 6,
    courseName: 'Complete React Developer',
    instructorName: 'Andrei Neagoie',
    img: 'https://img-a.udemycdn.com/course/750x422/2365628_0b60_7.jpg',
    price: 12.0,
  },
  {
    id: 7,
    courseName: 'Complete Web Development Course',
    instructorName: 'Jhankar Mahbub',
    img:
      'https://bangla2.programming-hero.com/wp-content/uploads/2020/06/HTML_CSS_Cover.png',
    price: 8.0,
  },
  {
    id: 8,
    courseName: 'The Complete JavaScript Course 2020: Build Real Projects!',
    instructorName: 'Jonas Schmedtmann',
    img: 'https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg',
    price: 9.99,
  },
  {
    id: 9,
    courseName: 'JavaScript Understanding the Weird Parts',
    instructorName: 'Anthony Alicea',
    img: 'https://img-a.udemycdn.com/course/240x135/364426_2991_5.jpg',
    price: 9.99,
  },
  {
    id: 10,
    courseName: 'Modern JavaScript From The Beginning',
    instructorName: 'Brad Traversy',
    img: 'https://img-a.udemycdn.com/course/240x135/1463348_52a4_2.jpg',
    price: 9.99,
  },
  {
    id: 11,
    courseName: 'Complete React Developer',
    instructorName: 'Andrei Neagoie',
    img: 'https://img-a.udemycdn.com/course/750x422/2365628_0b60_7.jpg',
    price: 12.0,
  },
  {
    id: 12,
    courseName: 'Complete Web Development Course',
    instructorName: 'Jhankar Mahbub',
    img:
      'https://bangla2.programming-hero.com/wp-content/uploads/2020/06/HTML_CSS_Cover.png',
    price: 8.0,
  },
  {
    id: 13,
    courseName: 'The Complete JavaScript Course 2020: Build Real Projects!',
    instructorName: 'Jonas Schmedtmann',
    img: 'https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg',
    price: 9.99,
  },
  {
    id: 14,
    courseName: 'JavaScript Understanding the Weird Parts',
    instructorName: 'Anthony Alicea',
    img: 'https://img-a.udemycdn.com/course/240x135/364426_2991_5.jpg',
    price: 9.99,
  },
  {
    id: 15,
    courseName: 'Modern JavaScript From The Beginning',
    instructorName: 'Brad Traversy',
    img: 'https://img-a.udemycdn.com/course/240x135/1463348_52a4_2.jpg',
    price: 9.99,
  },
]
